include("/Applications/CMake.app/Contents/share/cmake-4.4/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[run_host_tests]==]
  TEST_EXECUTABLE [==[/Users/ww/src/phase-box/build-host/tests/run_host_tests]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[/Users/ww/src/phase-box/build-host/tests]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[run_host_tests_TESTS]==]
  CTEST_FILE [==[/Users/ww/src/phase-box/build-host/tests/run_host_tests_e3b0c442_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[/Users/ww/src/phase-box/build-host/tests]==]
)
